apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1an5k47lwzqkn0rq0f796ayfwa6sd9qrp4y8vctc5fha3c3tpdv8sk6dr6s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWa2VWQlpra09IbVNFek50
            NXNtSEVkaTZUaXBoSnZmbHQ1WXlxbDN2RmxVClRPYS9UVFJLcGZOZTIyMS84bDhl
            SkJ5ZW4xcjNVc05SOWJnMUhLT1VzQzQKLS0tIDZRcTVmeUt6a3Z5RklOZlRRaW1t
            QVZxcGlQSzljSjBQUFFsRW91dy9rVU0KK7nvkcPjw8Dfm93rMkDjmt67fASW8ae1
            29YC3fy1Wu0EfQia/8z13LgIoZ2FGgO2+FJiU59F+wRJOmJ9Y4OPKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-19T20:01:39Z"
    mac: ENC[AES256_GCM,data:HduzsC/kjpKPI+piXKs1YAMdG75nyB3SHWb8nlKcTprV3fPCRbBhZ/pQ3OtA4r7LlXMFImfCdQGORo/L2RQL17myrLj3YnFM94uWZWIzB5VpXjmxN/1ZBwZ37WWBEtG/OFD8xaHek/thViBpXLcVMk8MYEvlhWRL7t+Brgh71uU=,iv:JNl03qqXLR9Jb3uvsek5itE9ayYwYrDgmwEG242dSAo=,tag:3kLnjVxXxGAm/pc+ax4YEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
