apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:b9vlvnGDlMwD5Z/kWBwEBLTsQXyWBcbl,iv:geUvaAqoCsglSjjjUHTmEZBreo3fBUADzlTfDqXk62Y=,tag:FIz++3bFQ3ZcIHL4+5rREA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1an5k47lwzqkn0rq0f796ayfwa6sd9qrp4y8vctc5fha3c3tpdv8sk6dr6s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SkRYVUN6VkJOSGg1aWNz
            SWE4aHZDUEpWNkoxakcvek1OenIybXFZekNVCkZzNFVidzZHbHNSbVFFWDNUbU9W
            U1JOZHVHSllYTFFFUnRjQ2NWdlJsUEUKLS0tIHdUSTRmVFBvdmlubGxzQzkzc2Vp
            dElXWFZwWEE4YnlRTTlXZTJEdEc3QmsKxeM88bhTMC4L8o8SBId6qLe3mjE2Z8ou
            1sDCPXApwvxZJAB2nCeoOjufbC8NKuxW4/83kdgUYiot0kNsTDIeug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T18:32:40Z"
    mac: ENC[AES256_GCM,data:nAct0zpfyKf00JA2qcxHQVPxW+uxH+//VsMeiUdWmzPfFlRBRz1r2JEoY/hSrZTHX1lia0KH+1hfx4rqsywTWDm+Fhjv0TEsuyaK/Nv+j0TK9vYmBmB/4MBiKKF0tvSZ9SDDf/pxTP0ZhKnhyT7fXxLqEJ7KRUmQUvRZSccYp+A=,iv:Yyxy/ti2WU0YXbAbPueVRRbuaRiOnaSFIh0eKnqdI7s=,tag:MuIf8aFSLpm/a1ZKIoa5xg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
