apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:DZqFzu2OFrz2gSHqM6TSG9KuepeaZK0se+bJIBHwkLVXAKSvDfkIVQ==,iv:IzMJxxGUMs+78VCnBJ9B7Ch9ULAY3CZS8su0I2rB/9s=,tag:65BLTWnVKYBQaMW0nF6lXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1an5k47lwzqkn0rq0f796ayfwa6sd9qrp4y8vctc5fha3c3tpdv8sk6dr6s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VDRvZFllN1FUNi9TZkpD
            dnVZZEErbXBvVTUzS0tkNmtuTnM0S3RuSFVvCkpzcCt4T1AvaXREUFZ4UjZUQ0Vv
            WExDSXV5ZnJRNVhRUzZ2SUVOOUVYMEkKLS0tIEVRZ3BMKzJaaXprb3dOb1FQZmpG
            enNiTDV2QmlyUGVWVjh0UkExUWEzVGMK8x0rk6dMHlFNPxKLaVsqz1k0jmXuNECt
            Oekrxr/X/XkYMM+sn5QrGHdqiLHxRHZtV71ATYmHj9TKiNOb6R1ToA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-19T20:01:38Z"
    mac: ENC[AES256_GCM,data:s17kk9iaANvRz5U6oGAhjJnA9Hu+v2fZbC7xeuvHh1WcOZgrwZqlkx1bgVvMOZI19zy2Ine5iVhO/Rxoa0ZPmgGBnJF9FsaVHZHz9YCpM1lJ3cIattq/ipV96/481GgMbpew+dPSdSotoJmUMqWLX2ZY9w/98CKZ8KSVCgXc79Y=,iv:qk2/5b7KhtV5A8Yg95T+IN9h55/4AjbtXItZc2vd0lI=,tag:bjoojK3UTheZDp9XCDQoPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
